- name: Scan SSH keys on host
  delegate_to: localhost
  shell: ssh-keyscan -H {{inventory_hostname}}
  register: sshkey

- name: Remove existing entries from known_hosts
  delegate_to: localhost
  known_hosts:
    name: "{{inventory_hostname}}"
    state: absent

- name: Add key to known_hosts
  delegate_to: localhost
  shell: echo "{{sshkey.stdout}}" >> ~/.ssh/known_hosts
