- hosts: gcp_role_beacon
  remote_user: ubuntu
  gather_facts: no
  strategy: free
  vars:
    role: beacon
    monitoring_ip: "{{ hostvars[groups['gcp_role_monitoring'][0]].ansible_default_ipv4.address }}"
  tasks:
    - name: SSH keyscan
      import_role:
        name: sshkeyscan
        tasks_from: sshkeyscan
      tags:
        - never
        - keyscan

    - name: Gather facts
      setup:
      tags:
        - never
        - gather

    - name: NTP
      import_role:
        name: ntp
        tasks_from: chrony
      tags:
        - ntp

    # Beacon
    - name: Copy beacon executable
      copy: src={{beacon_path}} dest=/home/ubuntu/beacon
              owner=ubuntu group=ubuntu mode=0744
      tags:
        - beacon

    # Supervisor
    - name: Install supervisor
      apt:
        name: supervisor
        update_cache: yes
      become: yes

    - name: Beacon config file
      copy: src=./beacon.conf dest=/etc/supervisor/conf.d/beacon.conf
              owner=ubuntu group=ubuntu mode=0644
      become: yes

    - name: Reload supervisor config
      supervisorctl:
        name: beacon
        state: present
      become: yes

    - name: Restart beacon
      supervisorctl:
        name: beacon
        state: restarted
      become: yes
      tags:
        - beacon

    # Filebeat
    - name: Filebeat install
      import_role:
        name: filebeat
        tasks_from: install
      tags:
        - filebeat

    - name: Filebeat config
      template:
        src: ./filebeat.yml.j2
        dest: /etc/filebeat/filebeat.yml
        owner: root
        group: root
        mode: 0744
      become: yes
      tags:
        - filebeat

    - name: Restart filebeat
      shell: service filebeat restart
      become: yes
      tags:
        - filebeat
