- name: SSH keyscan
  import_role:
    name: sshkeyscan
    tasks_from: sshkeyscan
  tags:
    - never
    - keyscan

- name: Gather facts
  setup:
  tags:
    - never
    - gather

- name: NTP
  import_role:
    name: ntp
    tasks_from: chrony
  tags:
    - ntp

# Buffer sizes
- name: Buffer sizes
  import_role:
    name: netbuffer
    tasks_from: main
  tags:
    - buffer

# Supervisor
- name: Supervisor install
  import_role:
    name: supervisor
    tasks_from: install
  tags:
    - supervisor

# chain
- name: Copy chain executable
  copy: src={{chain_path}} dest=/home/ubuntu/chain
          owner=ubuntu group=ubuntu mode=0744
  tags:
    - chain

# - name: Copy chain genesis
#   copy: src={{chain_genesis_path}} dest=/home/ubuntu/genesis.json
#           owner=ubuntu group=ubuntu mode=0744
#   tags:
#     - chainreset
#     - never

# - name: Init chain
#   shell: sudo rm -rf /home/ubuntu/chaindata && /home/ubuntu/chain --datadir /home/ubuntu/chaindata init /home/ubuntu/genesis.json
#   tags:
#     - chainreset
#     - never

# - name: Copy chain config
#   copy: src={{chain_config_path}} dest=/home/ubuntu/chain.config
#           owner=ubuntu group=ubuntu mode=0744
#   tags:
#     - chain

- name: chain config
  import_role:
    name: supervisor
    tasks_from: config
  vars:
    process_name: chain
  tags:
    - chain

# relay
- name: Copy relay executable
  copy: src={{relay_path}} dest=/home/ubuntu/relay
          owner=ubuntu group=ubuntu mode=0744
  tags:
    - relay

- name: Relay config
  import_role:
    name: supervisor
    tasks_from: config
  vars:
    process_name: relay
  tags:
    - relay

# Filebeat
- name: Filebeat install
  import_role:
    name: filebeat
    tasks_from: install
  tags:
    - filebeat

- name: Filebeat config
  template:
    src: ./filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: 0744
  become: yes
  tags:
    - filebeat

- name: Start filebeat
  shell: service filebeat restart
  become: yes
  tags:
    - filebeat

- name: Nuke logs
  shell: rm -rf /var/log/supervisor/relay*
  become: yes
  tags:
    - never
    - lognuke
