- name: Config file
  block:
    - name: File
      copy: src={{config_path}} dest=/etc/supervisor/conf.d/{{config_path}}
            owner=ubuntu group=ubuntu mode=0644
      become: yes
  rescue:
    - name: Template
      template: src={{config_path}}.j2 dest=/etc/supervisor/conf.d/{{config_path}}
                owner=ubuntu group=ubuntu mode=0644
      become: yes

- name: Load config
  supervisorctl:
    name: "{{process_name}}"
    state: present
  become: yes

- name: Restart process
  supervisorctl:
    name: "{{process_name}}"
    state: restarted
  become: yes
