- hosts: gcp_role_relay
  remote_user: ubuntu
  gather_facts: no
  strategy: free
  vars:
    role: relay
  tasks:
    - name: SSH keyscan
      import_role:
        name: sshkeyscan
        tasks_from: sshkeyscan
      tags:
        - never
        - keyscan

    - name: NTP
      import_role:
        name: ntp
        tasks_from: chrony
      tags:
        - ntp

    # Buffer sizes
    - name: Set udp memory
      shell: sudo echo -e "26214400\t26214400\t26214400" > /proc/sys/net/ipv4/udp_mem
      become: yes
      tags:
        - buffer

    - name: Set read memory max
      shell: sysctl -w net.core.rmem_max=26214400
      become: yes
      tags:
        - buffer

    - name: Set write memory max
      shell: sysctl -w net.core.wmem_max=26214400
      become: yes
      tags:
        - buffer

    - name: Set read memory default
      shell: sysctl -w net.core.rmem_default=26214400
      become: yes
      tags:
        - buffer

    - name: Set write memory default
      shell: sysctl -w net.core.wmem_default=26214400
      become: yes
      tags:
        - buffer

    # relay
    - name: Copy relay executable
      copy: src={{relay_path}} dest=/home/ubuntu/relay
              owner=ubuntu group=ubuntu mode=0744
      tags:
        - relay

    # Node exporter
    # - name: Copy node exporter executable
    #   copy: src={{node_exporter_path}} dest=/home/ubuntu/node_exporter
    #           owner=ubuntu group=ubuntu mode=0744

    # Supervisor
    - name: Install supervisor
      apt:
        name: supervisor
        update_cache: yes
      become: yes

    - name: Relay config file
      copy: src=./relay.conf dest=/etc/supervisor/conf.d/relay.conf
              owner=ubuntu group=ubuntu mode=0644
      become: yes
      tags:
        - config

    # - name: Node exporter config file
    #   copy: src=./node_exporter.conf dest=/etc/supervisor/conf.d/node_exporter.conf
    #           owner=ubuntu group=ubuntu mode=0644
    #   become: yes

    - name: Reload supervisor config
      command: supervisorctl reload
      become: yes
      tags:
        - config

    - name: Restart relay
      supervisorctl:
        name: relay
        state: restarted
      become: yes
      tags:
        - relay

    - name: Stop relay
      supervisorctl:
        name: relay
        state: stopped
      become: yes
      tags:
        - never
        - stop

    # Filebeat
    - name: Add filebeat apt key
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present
      become: yes
      tags:
        - filebeat

    - name: Add filebeat apt repo
      apt_repository:
        repo: deb https://artifacts.elastic.co/packages/oss-7.x/apt stable main
        state: present
        filename: elastic-7.x
      become: yes
      tags:
        - filebeat

    - name: Install filebeat
      apt:
        name: filebeat
        update_cache: yes
      become: yes
      tags:
        - filebeat

    - name: Filebeat config
      template:
        src: ./filebeat.yml.j2
        dest: /etc/filebeat/filebeat.yml
        owner: root
        group: root
        mode: 0744
      become: yes
      tags:
        - filebeat

    - name: Start filebeat
      shell: service filebeat restart
      become: yes
      tags:
        - filebeat

    - name: Nuke logs
      shell: rm -rf /var/log/supervisor/relay*
      become: yes
      tags:
        - never
        - lognuke
