# NTP
- name: NTP time sync
  apt:
    name: chrony
    update_cache: yes
  become: yes
  tags:
    - ntp

# Buffer sizes
- name: Set udp memory
  shell: sudo echo -e "26214400\t26214400\t26214400" > /proc/sys/net/ipv4/udp_mem
  become: yes
  tags:
    - buffer

- name: Set read memory max
  shell: sysctl -w net.core.rmem_max=26214400
  become: yes
  tags:
    - buffer

- name: Set write memory max
  shell: sysctl -w net.core.wmem_max=26214400
  become: yes
  tags:
    - buffer

- name: Set read memory default
  shell: sysctl -w net.core.rmem_default=26214400
  become: yes
  tags:
    - buffer

- name: Set write memory default
  shell: sysctl -w net.core.wmem_default=26214400
  become: yes
  tags:
    - buffer

# Ephemeral storage
- name: Create filesystem
  block:
    - name: Create filesystem
      filesystem:
        fstype: ext4
        dev: /dev/nvme0n1
      become: yes

    - name: Mount filesystem
      mount:
        path: /home/ubuntu/eth_data
        state: mounted
        src: /dev/nvme0n1
        fstype: ext4
      become: yes

    - name: Permissions
      file:
        path: /home/ubuntu/eth_data
        state: directory
        recurse: yes
        owner: ubuntu
        group: ubuntu
      become: yes
  rescue:
    - name: Create filesystem
      filesystem:
        fstype: ext4
        dev: /dev/nvme1n1
      become: yes

    - name: Mount filesystem
      mount:
        path: /home/ubuntu/eth_data
        state: mounted
        src: /dev/nvme1n1
        fstype: ext4
      become: yes

    - name: Permissions
      file:
        path: /home/ubuntu/eth_data
        state: directory
        recurse: yes
        owner: ubuntu
        group: ubuntu
      become: yes
  tags:
    - ssd

# Parity
- name: Copy pwd file
  copy: src=./node.pwds dest=/home/ubuntu/node.pwds
          owner=ubuntu group=ubuntu mode=0644
  tags:
    - parity

- name: Copy parity executable
  copy: src={{parity_path}} dest=/home/ubuntu/parity
          owner=ubuntu group=ubuntu mode=0744
  tags:
    - parity

# onramp
- name: Copy onramp executable
  copy: src={{onramp_path}} dest=/home/ubuntu/onramp
          owner=ubuntu group=ubuntu mode=0744
  tags:
    - onramp

- name: Copy key
  copy: src={{onramp_key_path}} dest=/home/ubuntu/pkey.ec.der
          owner=ubuntu group=ubuntu mode=0744
  tags:
    - onramp

# Supervisor
- name: Install supervisor
  apt:
    name: supervisor
    update_cache: yes
  become: yes

- name: Parity config file
  copy: src=./parity.conf dest=/etc/supervisor/conf.d/parity.conf
          owner=ubuntu group=ubuntu mode=0644
  become: yes
  tags:
    - config

- name: OnRamp config file
  copy: src=./onramp.conf dest=/etc/supervisor/conf.d/onramp.conf
          owner=ubuntu group=ubuntu mode=0644
  become: yes
  tags:
    - config

- name: Reload supervisor config
  command: supervisorctl reload
  become: yes
  tags:
    - config
