- name: Create filesystem
  block:
    - name: Create filesystem
      filesystem:
        fstype: ext4
        dev: /dev/nvme0n1
      become: yes

    - name: Mount filesystem
      mount:
        path: "{{mount_point}}"
        state: mounted
        src: /dev/nvme0n1
        fstype: ext4
      become: yes

    - name: Permissions
      file:
        path: "{{mount_point}}"
        state: directory
        recurse: yes
        owner: ubuntu
        group: ubuntu
      become: yes
  rescue:
    - name: Create filesystem
      filesystem:
        fstype: ext4
        dev: /dev/nvme1n1
      become: yes

    - name: Mount filesystem
      mount:
        path: "{{mount_point}}"
        state: mounted
        src: /dev/nvme1n1
        fstype: ext4
      become: yes

    - name: Permissions
      file:
        path: "{{mount_point}}"
        state: directory
        recurse: yes
        owner: ubuntu
        group: ubuntu
      become: yes
  tags:
    - ssd
