- hosts: gcp_role_eth
  remote_user: ubuntu
  gather_facts: no
  strategy: free
  vars:
    role: eth
    monitoring_ip: "{{ hostvars[groups['gcp_role_monitoring'][0]].ansible_default_ipv4.address }}"
    beacon_ip: "{{ hostvars[groups['gcp_role_beacon'][0]].ansible_default_ipv4.address }}"
  tasks:
    - name: SSH keyscan
      import_role:
        name: sshkeyscan
        tasks_from: sshkeyscan
      tags:
        - never
        - keyscan

    - name: NTP
      import_role:
        name: ntp
        tasks_from: chrony
      tags:
        - ntp

    # Buffer sizes
    - name: Buffer sizes
      import_role:
        name: netbuffer
        tasks_from: main
      tags:
        - buffer

    # Ephemeral storage
    - name: Mount local ssd
      import_role:
        name: localssd
        tasks_from: main
      vars:
        mount_point: /home/ubuntu/eth_data
      tags:
        - ssd

    # Supervisor
    - name: Supervisor install
      import_role:
        name: supervisor
        tasks_from: install
      tags:
        - supervisor

    # bridge
    - name: Copy bridge executable
      copy: src={{bridge_path}} dest=/home/ubuntu/bridge
              owner=ubuntu group=ubuntu mode=0744
      tags:
        - bridge

    - name: Copy bridge key
      copy: src=./pkey.ec.der dest=/home/ubuntu/pkey.ec.der
              owner=ubuntu group=ubuntu mode=0777
      tags:
        - bridge

    - name: bridge config
      import_role:
        name: supervisor
        tasks_from: config
      vars:
        process_name: bridge
      tags:
        - bridge

    # Copy chaindata
    - name: Copy chaindata
      shell: mkdir -p /home/ubuntu/eth_data/geth && gsutil cp gs://marlin-chaindata-iowa/eth.tar - | tar -xf - -C /home/ubuntu/eth_data/geth/
      become: yes
      tags:
        - never
        - chaindata

    # chain
    - name: Copy chain executable
      copy: src={{chain_path}} dest=/home/ubuntu/chain
              owner=ubuntu group=ubuntu mode=0744
      tags:
        - chain

    - name: Add bridge as static peer
      copy: src=./static-nodes.json dest=/home/ubuntu/eth_data/static-nodes.json
              owner=ubuntu group=ubuntu mode=0777
      tags:
        - chain

    - name: chain config
      import_role:
        name: supervisor
        tasks_from: config
      vars:
        process_name: chain
      tags:
        - chain

    # Supervisor
    - name: Install supervisor
      apt:
        name: supervisor
        update_cache: yes
      become: yes
      tags:
        - supervisor

    - name: eth config file
      copy: src=./eth.conf dest=/etc/supervisor/conf.d/eth.conf
              owner=ubuntu group=ubuntu mode=0644
      become: yes
      tags:
        - config

    - name: Reload supervisor config
      command: supervisorctl reload
      become: yes
      tags:
        - config

    - name: Stop chain
      supervisorctl:
        name: chain
        state: stopped
      become: yes
      tags:
        - never
        - stop

    # Filebeat
    - name: Add filebeat apt key
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present
      become: yes
      tags:
        - filebeat

    - name: Add filebeat apt repo
      apt_repository:
        repo: deb https://artifacts.elastic.co/packages/oss-7.x/apt stable main
        state: present
        filename: elastic-7.x
      become: yes
      tags:
        - filebeat

    # - name: Lock release
    #   shell: mv /var/cache/apt/archives/lock /var/cache/apt/archives/lock.bak
    #   become: yes
    #   tags:
    #     - never
    #     - lockrel

    - name: Install filebeat
      apt:
        name: filebeat
        # update_cache: yes
        # force_apt_get: yes
      become: yes
      tags:
        - filebeat

    - name: Filebeat config
      template:
        src: ./filebeat.yml.j2
        dest: /etc/filebeat/filebeat.yml
        owner: root
        group: root
        mode: 0744
      become: yes
      tags:
        - filebeat

    - name: Start filebeat
      shell: service filebeat restart
      become: yes
      tags:
        - filebeat

    - name: Nuke logs
      shell: rm -rf /var/log/supervisor/bridge*
      become: yes
      tags:
        - never
        - lognuke
