- hosts: gcp_role_beacon
  remote_user: ubuntu
  gather_facts: no
  strategy: free
  vars:
    role: beacon
  tasks:
    - name: SSH keyscan
      import_role:
        name: sshkeyscan
        tasks_from: sshkeyscan
      tags:
        - never
        - keyscan

    - name: NTP
      import_role:
        name: ntp
        tasks_from: chrony
      tags:
        - ntp
