- hosts: gcp_role_master
  remote_user: ubuntu
  gather_facts: no
  strategy: free
  vars:
    role: master
    monitoring_ip: "{{ hostvars[groups['gcp_role_monitoring'][0]].ansible_default_ipv4.address }}"
    beacon_ip: "{{ hostvars[groups['gcp_role_beacon'][0]].ansible_default_ipv4.address }}"
  tasks:
    - name: SSH keyscan
      import_role:
        name: sshkeyscan
        tasks_from: sshkeyscan
      tags:
        - never
        - keyscan

    - name: NTP
      import_role:
        name: ntp
        tasks_from: chrony
      tags:
        - ntp

    # Buffer sizes
    - name: Buffer sizes
      import_role:
        name: netbuffer
        tasks_from: main
      tags:
        - buffer

    # Supervisor
    - name: Supervisor install
      import_role:
        name: supervisor
        tasks_from: install
      tags:
        - supervisor

    # master
    - name: Copy master executable
      copy: src={{master_path}} dest=/home/ubuntu/master
              owner=ubuntu group=ubuntu mode=0744
      tags:
        - master

    - name: Master config
      import_role:
        name: supervisor
        tasks_from: config
      vars:
        process_name: master
      tags:
        - master

    # Filebeat
    - name: Filebeat install
      import_role:
        name: filebeat
        tasks_from: install
      tags:
        - filebeat

    - name: Filebeat config
      template:
        src: ./filebeat.yml.j2
        dest: /etc/filebeat/filebeat.yml
        owner: root
        group: root
        mode: 0744
      become: yes
      tags:
        - filebeat

    - name: Start filebeat
      shell: service filebeat restart
      become: yes
      tags:
        - filebeat

    - name: Nuke logs
      shell: rm -rf /var/log/supervisor/master*
      become: yes
      tags:
        - never
        - lognuke
