- hosts: gcp_role_master
  remote_user: ubuntu
  gather_facts: no
  strategy: free
  vars:
    role: master
    monitoring_ip: "{{ hostvars[groups['gcp_role_monitoring'][0]].ansible_default_ipv4.address }}"
    beacon_ip: "{{ hostvars[groups['gcp_role_beacon'][0]].ansible_default_ipv4.address }}"
  tasks:
    - name: Master
      import_role:
        name: master
        tasks_from: main
