- hosts: gcp_role_monitoring
  remote_user: ubuntu
  gather_facts: no
  strategy: free
  vars:
    role: monitoring
  tasks:
    # NTP
    - name: NTP time sync
      apt:
        name: chrony
        update_cache: yes
      become: yes
      tags:
        - ntp

    - name: Add ES apt key
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present
      become: yes

    - name: Add ES apt repo
      apt_repository:
        repo: deb https://artifacts.elastic.co/packages/oss-7.x/apt stable main
        state: present
        filename: elastic-7.x
      become: yes

    - name: Install ES
      apt:
        name: elasticsearch-oss
        update_cache: yes
      become: yes

    - name: (Re)start ES
      shell: service elasticsearch restart
      become: yes
      tags:
        - es
