- hosts: gcp_role_monitoring
  remote_user: ubuntu
  gather_facts: no
  strategy: free
  vars:
    role: monitoring
  tasks:
    # NTP
    - name: NTP time sync
      apt:
        name: chrony
        update_cache: yes
      become: yes
      tags:
        - ntp

    - name: Add ES apt key
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present
      become: yes

    - name: Add ES apt repo
      apt_repository:
        repo: deb https://artifacts.elastic.co/packages/oss-7.x/apt stable main
        state: present
        filename: elastic-7.x
      become: yes

    - name: Install ES
      apt:
        name: elasticsearch-oss
        update_cache: yes
      become: yes

    - name: (Re)start ES
      shell: service elasticsearch restart
      become: yes
      tags:
        - es

    - name: Install Kibana
      apt:
        name: kibana-oss
        update_cache: yes
      become: yes

    - name: (Re)start Kibana
      shell: service kibana restart
      become: yes
      tags:
        - kibana

    - name: Install logstash
      apt:
        name: logstash-oss
        update_cache: yes
      become: yes
      tags:
        - logstash

    - name: (Re)start logstash
      shell: service logstash restart
      become: yes
      tags:
        - logstash

    - name: Install nginx
      apt:
        name: nginx
        update_cache: yes
      become: yes

    - name: Copy nginx config
      copy: src=./kibana dest=/etc/nginx/sites-available/kibana
              owner=ubuntu group=ubuntu mode=0644
      become: yes
      tags:
        - nginx

    - name: Symlink nginx config
      file:
        src: /etc/nginx/sites-available/kibana
        dest: /etc/nginx/sites-enabled/kibana
        owner: ubuntu
        group: ubuntu
        state: link
      become: yes

    - name: Reload nginx
      shell: service nginx reload
      become: yes
      tags:
        - nginx
